### PR TITLE
[READY] upgrade to rails 4.2.0

### PR DESCRIPTION
**Pull request by jurre**
Specs are all passing now but we're having to use the development branch of the Apartment gem so we should probably hold off merging.

### CODE REVIEW

**Comment by fatboypunk** [comment]
The Apartment gem has released v0.26.0 which contains support for rails 4.2.0 so I updated our gemfile with that. I removed the bang after the switch on `Apartment::Tenant.switch!("tenant_name")`. And it's rebased on development. 

Things left:
- [ ] Remove deprecation warning
- [ ] Remove scaffold code
- something else?

**Comment by Marthyn** [comment]
tested, works fine :)

**Comment by jurre** [comment]
@fatboypunk so v0.26.0 doesn't contain the updated `!` syntax yet?

**Comment by fatboypunk** [comment]
No it doesn't

**Pull request merged**
