### PR TITLE
[Production] Audits, Edit projects, billable, archive, edit category, improved charts, and some other stuf

### PR DESCRIPTION
**Pull request by fatboypunk**

### CODE REVIEW

**Comment by Marthyn** [comment]
This is not good to go yet, having problems with Project description on staging. 

```
2015-01-06T16:43:39.705733+00:00 app[web.1]: ActionView::Template::Error (undefined method `description' for #<Project:0x007f8fd61f2210>):
2015-01-06T16:43:39.705735+00:00 app[web.1]:     3:   .form-inputs
2015-01-06T16:43:39.705737+00:00 app[web.1]:     4:     = f.input :name, required: true, autofocus: true
2015-01-06T16:43:39.705739+00:00 app[web.1]:     5:     = f.association :client, required: false, collection: Client.by_name, label: false, placeholder: t("project.form.client"), include_blank: t("project.form.no_client")
2015-01-06T16:43:39.705741+00:00 app[web.1]:     6:     = f.input :description, as: :text, input_html: { rows: 5 }
2015-01-06T16:43:39.705743+00:00 app[web.1]:     7:     = f.label :billable
2015-01-06T16:43:39.705744+00:00 app[web.1]:     8:     = f.input :billable, as: :boolean, label: false
2015-01-06T16:43:39.705746+00:00 app[web.1]:     9:     = f.label :archived
2015-01-06T16:43:39.705748+00:00 app[web.1]:   app/views/projects/_form.html.haml:6:in `block in _app_views_projects__form_html_haml___2642773557795314457_70127870844220'
2015-01-06T16:43:39.705750+00:00 app[web.1]:   app/views/projects/_form.html.haml:1:in `_app_views_projects__form_html_haml___2642773557795314457_70127870844220'
2015-01-06T16:43:39.705751+00:00 app[web.1]:   app/views/projects/new.html.haml:4:in `_app_views_projects_new_html_haml___2001753673157321712_70127870894440'
2015-01-06T16:43:39.705753+00:00 app[web.1]:
2015-01-06T16:43:39.705754+00:00 app[web.1]:
```

But description does exist

```
=> #<Project id: 1, name: "CAPP", created_at: "2015-01-06 16:42:17", updated_at: "2015-01-06 16:42:17", slug: "capp", client_id: nil, archived: false, billable: false, budget: nil, description: nil>
irb(main):006:0> Project.new.description
=> nil
```

**Comment by jurre** [comment]
FYI this is not automatically deployed ^^

**Comment by Marthyn** [comment]
It is, i added a deploy script to Travis.yml

**Comment by jurre** [comment]
@Marthyn works for me on staging

**Comment by Marthyn** [comment]
With a new tenant and did you try to create a new project?

**Comment by fatboypunk** [comment]
Works for me too, (even adding a new project)

**Comment by Marthyn** [comment]
Then i guess it's fixed! :)
It didn't work for maarten yesterday when i left, but maybe he fixed it.

Date: Wed, 7 Jan 2015 01:28:40 -0800

**Comment by jurre** [comment]
@Marthyn on the defacto tenant

**Comment by Marthyn** [comment]
Then we can merge this imho

**Pull request merged**
