### PR TITLE
Send csv to email

### PR DESCRIPTION
**Pull request by RachelAbaniwo**
This PR adds the functionality to send the CSV format of a user's entries to  a specified email address.

#### Screenshots

screenshot 2019-02-13 at 1 15 41 am

screenshot 2019-02-13 at 1 27 48 am

screenshot 2019-02-13 at 1 29 02 am

screenshot 2019-02-13 at 1 20 56 am

screenshot 2019-02-13 at 1 20 22 am

### CODE REVIEW

**Comment by jurre** [comment]
Hi Rachel, it would be good to communicate about if we wish to support such a feature in an Issue first before implementing it.

Before diving into the code, I think we need to figure out if we want to add this in the first place.

**Comment by RachelAbaniwo** [comment]
okay @jurre this has been noted.

**Comment by jurre** [comment]
After thinking about it for a while, I don't really see the point of this feature, couldn't you just simply download the CSV and email it to whoever you'd like? Why does the app need to send the email?

**Comment by jurre** [comment]
We've decided to freeze feature development as none of the maintainers currently have time to properly steward contributions from the community.

**Pull request closed without merging**
