### PR TITLE
add application javascript improvements

### PR DESCRIPTION
**Pull request by herminiotorres**
- Add improvements in javascript application
- Fix TypeError no implicit conversion of Integer into String

### CODE REVIEW

**Comment by herminiotorres** [comment]
@jurre When are you going to do the happyhours codebase update?

I am already seeing how I will structure the i18n files and where the project need a Brazilian Portuguese translation.

**Comment by jurre** [comment]
You mean deploy it to production for happyhours.io?

**Comment by herminiotorres** [comment]
Yes.

**Comment by jurre** [comment]
@fatboypunk do you think you could do it today or tomorrow? I believe I don't have access to the production instance anymore

**Comment by fatboypunk** [comment]
> @fatboypunk do you think you could do it today or tomorrow? I believe I don't have access to the production instance anymore

You can't create a PR to master? But sure will do it

**Comment by jurre** [comment]
> You can't create a PR to master? But sure will do it

Ah, we auto-deploy master, right 👍 I _can_ actually do that :p

**Pull request merged**
