### PR TITLE
[WIP] No more pagination

### PR DESCRIPTION
**Pull request by tarzan**
no pagination might be a problem without lazy loading though....

### CODE REVIEW

**Comment by Marthyn** [comment]
what.. why no pagination?

**Comment by tarzan** [comment]
'cause it's really bad UX; say I'm looking for a particular project; how am I supposed to find it? Browse through the pages? Would much rather use CMD+F as would every sane human being.

**Comment by Marthyn** [comment]
Or a search function. Removing pagination will cause insane load times

**Comment by tarzan** [comment]
`billables` and `reports` both don't even have pagination!

**Comment by Marthyn** [comment]
Reports do, billables not i remember now.
screen shot 2015-02-26 at 15 13 02

**Comment by fatboypunk** [comment]
> 'cause it's really bad UX; say I'm looking for a particular project; how am I supposed to find it? Browse through the pages? Would much rather use CMD+F as would every sane human being.

Still sucks with lazy loading as well

**Comment by jurre** [comment]
Just add search?

**Comment by tarzan** [comment]
doesn't need to be... depends on what we lazy load -> can't we just do lazy_loading on the numbers/donuts etc of projects?

**Comment by fatboypunk** [comment]
> Just add search?

Seems to be easier than

> can't we just do lazy_loading on the numbers/donuts etc of projects?

**Comment by jurre** [comment]
@tarzan could we close this PR?

**Comment by tarzan** [comment]
yup

**Pull request closed without merging**
