### PR TITLE
Add contact us for guest

### PR DESCRIPTION
**Pull request by omedale**
### Feature
- This PR adds functionality that allows guests to send admin a message 

### Note
- For admin to easily access the messages from the database, a message page should be added to admin dashboard to populate messages

### Screenshot
screenshot 2018-10-07 at 8 22 41 am

### CODE REVIEW

**Comment by jurre** [comment]
I'm not sure that I see the need for this type of feature? What's the idea behind this?

Wouldn't it be easier to just add something like Intercom?

**Comment by omedale** [comment]
We have a functionality like this inside the app, but you have have to sign in to access this functionality. This new one will be useful for both users and visitors. 
We could integrate `Intercom` which I believe is a paid service, and we might need a dedicated person to be online to respond to enquires  `Intercom` bot won't have answers to.
With this we can get feedback or complains from visitors or users and we respond to them accordingly

**Comment by jurre** [comment]
I don't really see the need for this, maybe just add an email address where people can reach you on the homepage somewhere?

This doesn't really feel like a common enough use case to add support for it to be honest.

**Comment by jurre** [comment]
We've decided to freeze feature development as none of the maintainers currently have time to properly steward contributions from the community.

**Pull request closed without merging**
