### PR TITLE
Fix bundler warning: this Gemfile contains multiple primary sources

### PR DESCRIPTION
**Pull request by takiy33**
The following warning is occured when I execute *bundle install* .

```
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. 
To resolve this warning, use a block to indicate which gems should come from the secondary source.
To upgrade this warning to an error, run `bundle config disable_multisource true`.
```

### CODE REVIEW

**Comment by jurre** [comment]
Awesome! Is that the only rails-assets gem we're using?

**Comment by takiy33** [comment]
I am not sure.I try to check it.

**Comment by jurre** [comment]
It is :)

**Comment by takiy33** [comment]
> Awesome! Is that the only rails-assets gem we're using?

Yes it is. I think that chart-js-rails gem is not used.
But, I am not familiar with Rails.

**Pull request merged**
